# Test Fixture Auto-Generation Script (ASCII-safe)
# Usage: From project root:
#   .\test\fixtures\generate.ps1
#
# Note: This script is intentionally written in pure ASCII to avoid
# Windows PowerShell 5.1 encoding issues with Korean text in scripts.
# Korean content is generated by converting from existing utf8-korean.txt.

$ErrorActionPreference = 'Stop'
$dir = $PSScriptRoot

Write-Host "Fixture generation started: $dir" -ForegroundColor Cyan

# 1) CP949 Korean file (converted from utf8-korean.txt)
$utf8Path = Join-Path $dir "utf8-korean.txt"
if (Test-Path $utf8Path) {
    $utf8Content = [System.IO.File]::ReadAllText($utf8Path, [System.Text.Encoding]::UTF8)
    $cp949Bytes = [System.Text.Encoding]::GetEncoding(949).GetBytes($utf8Content)
    [System.IO.File]::WriteAllBytes((Join-Path $dir "cp949-korean.txt"), $cp949Bytes)
    Write-Host ("  [+] cp949-korean.txt ({0} bytes from utf8-korean.txt)" -f $cp949Bytes.Length) -ForegroundColor Green
} else {
    Write-Host "  [!] utf8-korean.txt not found - skipping CP949" -ForegroundColor Yellow
}

# 2) UTF-8 BOM file (ASCII content only)
$bomText = "BOM test file" + [char]13 + [char]10 + "Second line" + [char]13 + [char]10 + "Third line"
$utf8WithBom = New-Object System.Text.UTF8Encoding $true
$bomBytes = $utf8WithBom.GetPreamble() + $utf8WithBom.GetBytes($bomText)
[System.IO.File]::WriteAllBytes((Join-Path $dir "utf8-bom.txt"), $bomBytes)
Write-Host ("  [+] utf8-bom.txt ({0} bytes, BOM included)" -f $bomBytes.Length) -ForegroundColor Green

# 3) Fake binary file (lots of null bytes)
$binBytes = New-Object byte[] 1024
$rand = New-Object System.Random
for ($i = 0; $i -lt 1024; $i++) {
    if ($i % 5 -eq 0) {
        $binBytes[$i] = 0
    } else {
        $binBytes[$i] = [byte]$rand.Next(1, 255)
    }
}
[System.IO.File]::WriteAllBytes((Join-Path $dir "fake-binary.bin"), $binBytes)
Write-Host "  [+] fake-binary.bin (1024 bytes, ~20% null bytes)" -ForegroundColor Green

# 4) CRLF / LF comparison files (ASCII)
$crlf = "line 1" + [char]13 + [char]10 + "line 2" + [char]13 + [char]10 + "line 3"
$lf = "line 1" + [char]10 + "line 2" + [char]10 + "line 3"
[System.IO.File]::WriteAllBytes((Join-Path $dir "crlf.txt"), [System.Text.Encoding]::UTF8.GetBytes($crlf))
[System.IO.File]::WriteAllBytes((Join-Path $dir "lf.txt"), [System.Text.Encoding]::UTF8.GetBytes($lf))
Write-Host "  [+] crlf.txt + lf.txt" -ForegroundColor Green

Write-Host ""
Write-Host "All fixtures:" -ForegroundColor Cyan
Get-ChildItem $dir -File | Format-Table Name, Length, LastWriteTime -AutoSize
